# Generated by Django 5.2 on 2025-05-17 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('founder', models.CharField(blank=True, max_length=100, null=True)),
                ('origin_date', models.CharField(blank=True, max_length=50, null=True)),
                ('origin_place', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
